---
layout: post
title: "4. Show and Tell (im2txt)"
description : TensorFlow의 여러가지 모델 중 im2txt의 사용을 해보겠습니다. Github의 사용법에 따라 실행하다보면 예기치 않은 오류가 발생하는데 그에 대한 원인과 해결방법을 알아보겠습니다.
tag: capstone
---

앞서 방법론에서 말씀드렸듯이 저희는 'Show and Tell'의 논문과 'Manhattan LSTM' 모델을 활용할 것입니다.
우선 첫번째로 'Show and Tell'을 적용시킨 TensorFlow im2txt를 사용해보겠습니다.

현재 tensorflow의 버전은 r1.4까지 업데이트가 되었습니다. 제가 처음 tensorflow를 접하고 공부할 때는 r1.0이었습니다. 그때도 im2txt를 사용해보려했는데, 실행조차 못시키다가 r1.3버전에서 숱한 오류를 만나고 찾으면서 겨우 실행을 시켰습니다.

이제 그 원인과 해결방법에 대해 알아보겠습니다.

1. [기본설치](#1-기본설치)
2. [TensorFlow Models 다운로드](#2-tensorflow-models-다운로드)
3. [Pre-trained Data : Checkpoint, wordcount](#3-pre-trained-data--checkpoint-wordcount)
4. [실행 1차 시도](#4-실행-1차-시도)
5. [Error 해결](#5-error-해결)
  - [경우 1 : word_count.txt](#error-1-word-count)
  - [경우 2 : ckpt 파일을 읽을 수 없는 문제](#error-2-ckpt)
  - [경우 3 : 파일 읽기 오류](#error-3-file-read)
6. [실행 2차 시도](#6-실행-2차-시도)

<br>

### 1. 기본설치
- Bazel
	``` shell
	$ sudo apt-get install openjdk-8-jdk
	$ sudo apt-get update && sudo apt-get install bazel
	$ sudo apt-get upgrade bazel
	```

- Natural Language Toolkit
	``` shell
	# sh
	$ source venv/bin/activate

	(venv)$ pip install -U nltk
	(venv)$ python
	```

	``` python
	# python3
	import nltk
	nltk.download()
	#
	# NLTK Downloader 창이 나오면 Download 클릭합니다.
	# 시간이 조금 많이 소요됩니다.
	```

	![nltk]({{ site.assets | absolute_url }}/capstone/4_nltk_download.png)

<br>

### 2. TensorFlow Models 다운로드
- TensorFlow는 정말 많은 모델을 지원합니다. 그중에 우리는 'Show and Tell'이 구현되어 이는 im2txt Model을 사용할 예정이기 때문에 우선 Models을 다운받아 놓습니다.

	``` shell
	$ git clone https://github.com/tensorflow/models.git
	```

- im2txt 를 시작하기 위해서 반드시 거쳐야 하는 과정이 있는데

<br>

### 3. Pre-trained Data : Checkpoint, wordcount
- Checkpoint
  : TensorFlow에서 모델을 만들고, 학습을 시키면서 parameter 값들이 제각기 자신의 위치를 찾아가게 되는데, 좋은 성능을 내는 순간의 parameter를 기록해 놓는 용도로 사용됩니다.

  - [im2txt_2016_10_05.1000000.tar.gz](https://drive.google.com/file/d/0Bw6m_66JSYLlNlRDUTRqcm9Jcjg/view)
  - [im2txt_2016_10_11.2000000.tar.gz](https://drive.google.com/file/d/0Bw6m_66JSYLlRFVKQ2tGcUJaWjA/view)

- wordcount
  :  이미지로부터 Caption을 만들기 위해서는 단어들이 있어야 하는데, 사용할 단어들을 모아둔 파일이 word_conunt.txt 입니다.
  - [word_count.txt](https://drive.google.com/file/d/0Bw6m_66JSYLleHdDNmpndjNPVDg/view)

- 직접 학습을 시키고 단어를 선정할 것이 아니라면, 한번 당장 사용하고 싶다 하면 **이 2가지 파일은 다운**받으시면 됩니다. 구글에 키워드로 'im2txt', 'pretrained'라고 검색해보면 다른 사람들이 학습시킨 파일이 쉽게 찾을 수 있습니다.

<br>

### 4. 실행 1차 시도
드디어 기본적인 준비가 다 되었습니다.
저는 [im2txt_2016_10_11.2000000.tar.gz](https://drive.google.com/file/d/0Bw6m_66JSYLlRFVKQ2tGcUJaWjA/view)을 다운받았고, [word_count.txt](https://drive.google.com/file/d/0Bw6m_66JSYLleHdDNmpndjNPVDg/view)도 받았습니다

```
your_workspace_path
│
├── checkpoint
│   ├── graph.pbtxt
│   ├── model.ckpt-2000000
│   └── model.ckpt-2000000.meta
│
├── models
│   ├── research
│   │   ├── im2txt
│   │   │   ├── g3doc
│   │   │   │   ├── COCO_val2014_000000224477.jpg
│   │   │   │   └── ...
│   │   │   ├── im2txt
│   │   │   │   └── ...
│   │   │   ├── README.md
│   │   │   └── WORKSPACE
│   │   └── ...
│   └── ...
│
├── venv
│   └── ...
│
└── word_counts.txt

```

``` shell
# Note: Absolute path
(venv)$ your_workspace_path="/absolute/path/your/workspace"

# Path to checkpoint file or a directory containing checkpoint files.
(venv)$ CHECKPOINT_PATH="${your_workspace_path}/checkpoint/model.ckpt-2000000"

# Vocabulary file generated by the preprocessing script.
(venv)$ VOCAB_FILE="${your_workspace_path}/word_counts.txt"

# JPEG image file to caption.
(venv)$ IMAGE_FILE="${your_workspace_path}/models/research/im2txt/g3doc/COCO_val2014_000000224477.jpg"

# Build the inference binary.
(venv)$ cd "${your_workspace_path}/models/research/im2txt"
(venv)$ bazel build -c opt //im2txt:run_inference

# Run inference to generate captions.
(venv)$ bazel-bin/im2txt/run_inference \
	  --checkpoint_path=${CHECKPOINT_PATH} \
	  --vocab_file=${VOCAB_FILE} \
	  --input_files=${IMAGE_FILE}
```

<br>

### 5. Error 해결

- 경우 1 : word_count.txt
{: #error-1-word-count}


``` shell
INFO: Analysed target //im2txt:run_inference (0 packages loaded).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.183s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /absolute/path/your/workspace/word_counts.txt
Traceback (most recent call last):
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
    tf.app.run()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 55, in main
    vocab = vocabulary.Vocabulary(FLAGS.vocab_file)
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/vocabulary.py", line 50, in __init__
    assert start_word in reverse_vocab
AssertionError
```

- 원인 :  이는 python2와 python3에서 문자열을 다루는 방식차이 때문에 발생한 결과인데, 우리가 다운받은 txt는 python2에서 저장한 방식이므로 python3로 새로 만들어주어야 합니다.

``` python
# python2 version
b'a' 969108
b'</S>' 586368
b'<S>' 586368
b'.' 440479
b'on' 213612
b'of' 202290
```

- 해결 : 결론적으론 word_count.txt 는 아래와 같은 방식으로 변경되어야 합니다. 그래야 지금 우리가 사용하고 있는 python3 환경에서 읽을 수 있습니다.

``` python
a 969108
</S> 586368
<S> 586368
. 440479
on 213612
of 202290
```

- 따라서 아래의 코드를 사용하여 word_count2.txt를 새로 만들도록 합시다.

``` python
OLD_VOCAB_FILE = "word_counts.txt"
NEW_VOCAB_FILE = "word_counts2.txt"

with open(OLD_VOCAB_FILE) as f:
  lines = list(f.readlines())

def clean_line(line):
  tokens = line.split()
  return "%s %s" % (eval(tokens[0]).decode('utf8'), tokens[1])

newlines = [clean_line(line) for line in lines]

with open(NEW_VOCAB_FILE, "w") as f:
  for line in newlines:
    f.write(line + "\n")
```

> **Note:** 파일 이름을 바꾸는 것도 잊지 마세요!
> ```shell
# (venv)$ VOCAB_FILE="${your_workspace_path}/word_counts.txt"
(venv)$ VOCAB_FILE="${your_workspace_path}/word_counts2.txt"
```

<br>

- 경우 2: ckpt 파일을 읽을 수 없는 문제
{: #error-2-ckpt}

``` shell
INFO: Analysed target //im2txt:run_inference (0 packages loaded).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.234s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /absolute/path/your/workspace/word_counts2.txt
INFO:tensorflow:Created vocabulary with 11520 words
INFO:tensorflow:Running caption generation on 1 files matching /absolute/path/your/workspace/models/research/im2txt/g3doc/COCO_val2014_000000224477.jpg
2017-12-25 05:29:20.644617: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Loading model from checkpoint: /absolute/path/your/workspace/checkpoint/model.ckpt-2000000
INFO:tensorflow:Restoring parameters from /absolute/path/your/workspace/checkpoint/model.ckpt-2000000
Traceback (most recent call last):
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lstm/basic_lstm_cell/kernel" not found in checkpoint files /absolute/path/your/workspace/checkpoint/model.ckpt-2000000
	 [[Node: save/RestoreV2_381 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_381/tensor_names, save/RestoreV2_381/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
    tf.app.run()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 65, in main
    restore_fn(sess)
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 96, in _restore_fn
    saver.restore(sess, checkpoint_path)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lstm/basic_lstm_cell/kernel" not found in checkpoint files /absolute/path/your/workspace/checkpoint/model.ckpt-2000000
	 [[Node: save/RestoreV2_381 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_381/tensor_names, save/RestoreV2_381/shape_and_slices)]]

Caused by op 'save/RestoreV2_381', defined at:
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
    tf.app.run()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 51, in main
    FLAGS.checkpoint_path)
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 116, in build_graph_from_config
    saver = tf.train.Saver()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/kernel" not found in checkpoint files /absolute/path/your/workspace/checkpoint/model.ckpt-2000000
	 [[Node: save/RestoreV2_381 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_381/tensor_names, save/RestoreV2_381/shape_and_slices)]]
```

- 원인 : tensorflow 는 지금까지 많은 업데이트를 거쳐왔습니다. r.14버전까지 im2txt에서 변수를 관리하는 tf.variable_scope의 명칭이 변하면서 우리가 다운받은 checkpoint 파일을 제대로 읽어들이지 못하는 것입니다.

``` shell
OLD_CHECKPOINT_FILE = "checkpoint/model.ckpt-2000000"

import tensorflow as tf

vars_name = set()

reader = tf.train.NewCheckpointReader(OLD_CHECKPOINT_FILE)
for old_name in reader.get_variable_to_shape_map():
  if 'lstm' in old_name:
    vars_name.add(old_name)

import pprint as pp
pp.pprint(vars_name)

# {'lstm/BasicLSTMCell/Linear/Matrix',
#  'lstm/BasicLSTMCell/Linear/Bias'}
```

- 따라서 아래의 오류로 추정해보건데 ```lstm/BasicLSTMCell/Linear/Matrix```는 ```lstm/basic_lstm_cell/kernel```로 바뀌어야 한다는 것을 알수 있습니다.

```
NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/kernel" not found in checkpoint files /absolute/path/your/workspace/checkpoint/model.ckpt-2000000
```

- 해결 : 이름을 찾을 수 없는 오류를 보고 tf.variable_scope를 변경하는 작업을 해줘야 합니다. 여러번 확인하면서 수정해야 합니다. 우선 아래 코드는 위의 오류를 모두 해결하고 새로운 checkpoint를 만드는 코드입니다.

``` python
OLD_CHECKPOINT_FILE = "checkpoint/model.ckpt-2000000"
NEW_CHECKPOINT_FILE = "checkpoint/model2.ckpt-2000000"

import tensorflow as tf
vars_to_rename = {
    "lstm/BasicLSTMCell/Linear/Matrix": "lstm/basic_lstm_cell/kernel",
    "lstm/BasicLSTMCell/Linear/Bias": "lstm/basic_lstm_cell/bias",
}
new_checkpoint_vars = {}
reader = tf.train.NewCheckpointReader(OLD_CHECKPOINT_FILE)
for old_name in reader.get_variable_to_shape_map():
  if old_name in vars_to_rename:
    new_name = vars_to_rename[old_name]
  else:
    new_name = old_name
  new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

init = tf.global_variables_initializer()
saver = tf.train.Saver(new_checkpoint_vars)

with tf.Session() as sess:
  sess.run(init)
  saver.save(sess, NEW_CHECKPOINT_FILE)
```
> **Note:** 파일 이름을 바꾸는 것도 잊지 마세요!
> ```shell
# (venv)$ CHECKPOINT_PATH="${your_workspace_path}/checkpoint/model.ckpt-2000000"
(venv)$ CHECKPOINT_PATH="${your_workspace_path}/checkpoint/model2.ckpt-2000000"
```

<br>

- 경우 3 : 파일 읽기 오류
{: #error-3-file-read}

``` shell
INFO: Analysed target //im2txt:run_inference (0 packages loaded).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.232s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /absolute/path/your/workspace/word_counts2.txt
INFO:tensorflow:Created vocabulary with 11520 words
INFO:tensorflow:Running caption generation on 1 files matching /absolute/path/your/workspace/models/research/im2txt/g3doc/COCO_val2014_000000224477.jpg
2017-12-25 05:57:48.116974: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Loading model from checkpoint: /absolute/path/your/workspace/checkpoint/model2.ckpt-2000000
INFO:tensorflow:Restoring parameters from /absolute/path/your/workspace/checkpoint/model2.ckpt-2000000
INFO:tensorflow:Successfully loaded checkpoint: model2.ckpt-2000000
Traceback (most recent call last):
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
    tf.app.run()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/absolute/path/your/workspace/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 74, in main
    image = f.read()
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 126, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 94, in _prepare_value
    return compat.as_str_any(val)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/absolute/path/your/workspace/venv/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

- 원인 : ```models/research/im2txt/im2txt/run_inference.py``` 의 73번째 줄인```with tf.gfile.GFile(filename, "r") as f:``` 는 이미지를 읽는 부분인데, 이미지는 binary로 읽어야 하므로 "rb"로 수정해야 합니다.

- 해결 :
``` python
# models/research/im2txt/im2txt/run_inference.py
# 72 lines
    for filename in filenames:
      # with tf.gfile.GFile(filename, "r") as f:
      with tf.gfile.GFile(filename, "rb") as f:
        image = f.read()
```

<br>

### 6. 실행 2차 시도
- 이제 다시 실행을 해봅시다.

```
your_workspace_path
│
├── checkpoint
│   ├── ...
│   ├── checkpoint
│   ├── model2.ckpt-2000000.data-00000-of-00001
│   ├── model2.ckpt-2000000.index
│   └── model2.ckpt-2000000.meta
│
├── models
│   ├── research
│   │   ├── im2txt
│   │   │   ├── g3doc
│   │   │   │   ├── COCO_val2014_000000224477.jpg
│   │   │   │   └── ...
│   │   │   ├── im2txt
│   │   │   │   └── ...
│   │   │   ├── README.md
│   │   │   └── WORKSPACE
│   │   └── ...
│   └── ...
│
├── venv
│   └── ...
│
└── word_counts.txt
```


``` shell
# Note: Absolute path
(venv)$ your_workspace_path="/absolute/path/your/workspace"

# Path to checkpoint file or a directory containing checkpoint files.
(venv)$ CHECKPOINT_PATH="${your_workspace_path}/checkpoint/model2.ckpt-2000000"

# Vocabulary file generated by the preprocessing script.
(venv)$ VOCAB_FILE="${your_workspace_path}/word_counts2.txt"

# JPEG image file to caption.
(venv)$ IMAGE_FILE="${your_workspace_path}/models/research/im2txt/g3doc/COCO_val2014_000000224477.jpg"

# Build the inference binary.
(venv)$ cd "${your_workspace_path}/models/research/im2txt"
(venv)$ bazel build -c opt //im2txt:run_inference

# Run inference to generate captions.
(venv)$ bazel-bin/im2txt/run_inference \
	  --checkpoint_path=${CHECKPOINT_PATH} \
	  --vocab_file=${VOCAB_FILE} \
	  --input_files=${IMAGE_FILE}
```

- 그럼 아래 이미지의 Caption의 결과를 얻을 수 있을 것입니다.

![sample1]({{ site.assets | absolute_url }}/capstone/4_sample1.jpg)

``` shell
INFO: Analysed target //im2txt:run_inference (0 packages loaded).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.194s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /absolute/path/your/workspace/word_counts2.txt
INFO:tensorflow:Created vocabulary with 11520 words
INFO:tensorflow:Running caption generation on 1 files matching /absolute/path/your/workspace/models/research/im2txt/g3doc/COCO_val2014_000000224477.jpg
2017-12-25 06:43:57.603649: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Loading model from checkpoint: /absolute/path/your/workspace/checkpoint/model2.ckpt-2000000
INFO:tensorflow:Restoring parameters from /absolute/path/your/workspace/checkpoint/model2.ckpt-2000000
INFO:tensorflow:Successfully loaded checkpoint: model2.ckpt-2000000
Captions for image COCO_val2014_000000224477.jpg:
  0) a man riding a wave on top of a surfboard . (p=0.035672)
  1) a person riding a surf board on a wave (p=0.016237)
  2) a man on a surfboard riding a wave . (p=0.010146)
```

<br>

![sample2]({{ site.assets | absolute_url }}/capstone/4_sample2.jpeg)

``` shell
INFO: Analysed target //im2txt:run_inference (0 packages loaded).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.205s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /absolute/path/your/workspace/word_counts2.txt
INFO:tensorflow:Created vocabulary with 11520 words
INFO:tensorflow:Running caption generation on 1 files matching /absolute/path/your/workspace/image/imain.jpeg
2017-12-25 06:51:36.075768: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Loading model from checkpoint: /absolute/path/your/workspace/checkpoint/model2.ckpt-2000000
INFO:tensorflow:Restoring parameters from /absolute/path/your/workspace/checkpoint/model2.ckpt-2000000
INFO:tensorflow:Successfully loaded checkpoint: model2.ckpt-2000000
Captions for image imain.jpeg:
  0) a man standing in a field with mountains in the background . (p=0.000106)
  1) a man standing in a field with a mountain in the background . (p=0.000075)
  2) a man standing in a field next to a forest . (p=0.000060)
```

